---
name: Push
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/inko:latest
    steps:
      - run: microdnf install --quiet --assumeyes tar git
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: test
        with:
          path: '~/.local/share/inko/packages'
          key: test-${{ hashFiles('inko.pkg') }}
      - run: inko --version
      - run: inko pkg sync
      - run: inko test
